### ISSUE TITLE
Bridge server IP problem ?

### ISSUE THREAD

**Issue by ariamohh** [miladrahimi/outline-bridge-server#7]
Hi there ,
what do you mean by change the hostname to the bridge server ip ? when I run docker-compose up -d 
it comes with an error , says the port is alreay in use , I changed the port in setup.py to something else and it says 

Recreating outline-bridge-server_v2ray_1 ... **done** 

thats it ? 

What should I write in hostname in outline manager ? should I use the same hostname that I wrote in Setup.py ? 

when I try to use the port that I entered in setup.py , the outline manager says that this port is in use

**Comment by miladrahimi** [comment]
<img width="850" alt="om" src="https://user-images.githubusercontent.com/6689295/209721471-b264b655-32f5-405b-9cb0-b5fb10557c16.png">

If you change the hostname in your Outline Manager to the bridge server IP address, it generates keys with the bridge IP address instead of the upstream IP address.

If the port is already used, change the port in your Outline Manager to another port and run the setup.py again then enter the new port.

**Comment by ariamohh** [comment]
Thanks ,
 I fixed it already
